### ISSUE TITLE
Boot fail using Everdrive GBA

### ISSUE THREAD

**Issue by Charlie22911** [veikkos/gba-frame-test#1]
The rom fails to boot with garbled logo on real hardware when using an Everdrive GBA.

**Comment by veikkos** [comment]
Hello, thanks for writing. Apparently Everdrive uses original BIOS so it's picky about the header of the ROM. The binary I'm sharing does not have copyrighted header to avoid any legal issues. If one wants to run the ROM on a target which requires the header, ROM needs to be "fixed" using [gbafix ](https://github.com/devkitPro/gba-tools/blob/master/src/gbafix.c)or similar solution.

Snippet from https://www.coranac.com/tonc/text/first.htm:

> If the intro screen shows “GameBoy” as normal, but the “Nintendo” at the bottom is garbled, you have a bad header. To get a valid header, use a program called gbafix.exe. This is originally by darkfader, but you can also find it at www.devkitpro.org.

The ROM without header has been tested on real hardware only using EZ Flash Omega.
